import Head from "next/head";
import { useContext } from "react";
import { ThemeContext } from "./api/context/themeContext";
import styles from "../styles/Home.module.css";

export default function Home() {
  const theme = useContext(ThemeContext);
  const darkMode = theme.state.darkMode;

  return (
    <div>
      <Head>
        <title>Traveloo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Main className={`bg ${darkMode ? "bg-dark" : "bg-light"}`}></Main>
    </div>
  );
}

const Main = styled.main`
  width: 1193px;
  height: 934px;

  .bg-dark {
    background-color: #1e1e1e;
  }

  .bg-light {
    background-color: #f4f5f7;
  }
`;
